Improvements and fixes

diff --git a/dns-policy-app/snap/hooks/configure b/dns-policy-app/snap/hooks/configure
--- a/dns-policy-app/snap/hooks/configure
+++ b/dns-policy-app/snap/hooks/configure
@@ -3,7 +3,7 @@
 # Copyright 2025 Canonical Ltd.
 # See LICENSE file for licensing details.
 
-DJANGO_DEBUG="$(snapctl get django-debug)"
+DJANGO_DEBUG="$(snapctl get debug)"
 export DJANGO_DEBUG
 
 case "$DJANGO_DEBUG" in
@@ -15,8 +15,38 @@ case "$DJANGO_DEBUG" in
     ;;
 esac
 
-DJANGO_ALLOWED_HOSTS="$(snapctl get django-allowed-hosts)"
+DJANGO_LOG_LEVEL="$(snapctl get log-level)"
+export DJANGO_LOG_LEVEL
+
+case "$DJANGO_LOG_LEVEL" in
+  "debug") ;;
+  "info") ;;
+  "warning") ;;
+  "error") ;;
+  "critical") ;;
+  "DEBUG") ;;
+  "INFO") ;;
+  "WARNING") ;;
+  "ERROR") ;;
+  "CRITICAL") ;;
+  *)
+    >&2 echo "'$DJANGO_LOG_LEVEL is not a supported value for debug. Possible values are debug, info, warning, error, critical"
+    return 1
+    ;;
+esac
+
+DJANGO_ALLOWED_HOSTS="$(snapctl get allowed-hosts)"
 export DJANGO_ALLOWED_HOSTS
+DJANGO_DATABASE_PASSWORD="$(snapctl get database-password)"
+export DJANGO_DATABASE_PASSWORD
+DJANGO_DATABASE_HOST="$(snapctl get database-host)"
+export DJANGO_DATABASE_HOST
+DJANGO_DATABASE_PORT="$(snapctl get database-port)"
+export DJANGO_DATABASE_PORT
+DJANGO_DATABASE_USER="$(snapctl get database-user)"
+export DJANGO_DATABASE_USER
+DJANGO_DATABASE_NAME="$(snapctl get database-name)"
+export DJANGO_DATABASE_NAME
 
 snapctl stop "$SNAP_INSTANCE_NAME"
 snapctl start "$SNAP_INSTANCE_NAME"
